function hRD = plugin_rd()
%PLUGIN_RD Reference design definition for Ultra96-V2 LPDDR4 access.

    hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Xilinx Vivado');

    hRD.ReferenceDesignName = 'Default system with External LPDDR4 Memory Access';
    hRD.BoardName = 'Avnet Ultra96-V2';
    hRD.SupportedToolVersion = {'2025.2'};

    hRD.addCustomVivadoDesign( ...
        'CustomBlockDesignTcl', 'system.tcl', ...
        'VivadoBoardPart', 'Avnet-tria:Ultra96v2:part0:1.3');

    add_clock_interface(hRD);
    add_control_interface(hRD);
    add_memory_interfaces(hRD);

    hRD.AddMATLABAXIManagerParameter = false;
    hRD.MATLABAXIManagerDefaultValue = 'off';
    hRD.HasProcessingSystem = true;
end

function add_clock_interface(hRD)
    hRD.addClockInterface( ...
        'ClockConnection', 'zynq_ultra_ps_e_0/pl_clk0', ...
        'ResetConnection', 'proc_sys_reset_0/peripheral_aresetn', ...
        'DefaultFrequencyMHz', 100, ...
        'MinFrequencyMHz', 5, ...
        'MaxFrequencyMHz', 250, ...
        'ClockModuleInstance', 'zynq_ultra_ps_e_0', ...
        'ClockNumber', 1);
end

function add_control_interface(hRD)
    hRD.addAXI4SlaveInterface( ...
        'InterfaceType', 'AXI4-Lite', ...
        'InterfaceID', 'AXI4-Lite', ...
        'InterfaceConnection', 'axi_ctrl_interconnect/M00_AXI', ...
        'BaseAddress', {'0xA0000000'}, ...
        'MasterAddressSpace', {'zynq_ultra_ps_e_0/Data'}, ...
        'IDWidth', 12, ...
        'HasProcessorConnection', true);
end

function add_memory_interfaces(hRD)
    add_axi_master( ...
        hRD, ...
        'gmem0', ...
        true, ...
        true, ...
        'axi_hp0_interconnect/S00_AXI', ...
        'zynq_ultra_ps_e_0/SAXIGP2/HP0_DDR_LOW', ...
        hex2dec('00000000'), ...
        hex2dec('10000000'));

    add_axi_master( ...
        hRD, ...
        'gmem1', ...
        true, ...
        false, ...
        'axi_hp1_interconnect/S00_AXI', ...
        'zynq_ultra_ps_e_0/SAXIGP3/HP1_DDR_LOW', ...
        hex2dec('20000000'), ...
        hex2dec('20000000'));

    add_axi_master( ...
        hRD, ...
        'gmem2', ...
        true, ...
        false, ...
        'axi_hp2_interconnect/S00_AXI', ...
        'zynq_ultra_ps_e_0/SAXIGP4/HP2_DDR_LOW', ...
        hex2dec('30000000'), ...
        hex2dec('30000000'));
end

function add_axi_master(hRD, interface_id, read_support, write_support, ...
                        connection, segment_name, read_base, write_base)
    hRD.addAXI4MasterInterface( ...
        'InterfaceID', interface_id, ...
        'IsRequired', false, ...
        'ReadSupport', read_support, ...
        'WriteSupport', write_support, ...
        'MaxDataWidth', 128, ...
        'AddrWidth', 32, ...
        'DefaultReadBaseAddr', read_base, ...
        'DefaultWriteBaseAddr', write_base, ...
        'InterfaceConnection', connection, ...
        'TargetAddressSegments', {{ ...
            segment_name, hex2dec('00000000'), hex2dec('80000000') ...
        }});
end
