classdef TestSolverIntegration < TestBase
%TESTSOLVERINTEGRATION End-to-end solver tests against reference behavior.

    properties (TestParameter)
        full_sweep_case = struct( ...
            'empty_6x6', struct('name', 'empty_6x6', ...
                                'mx', 6, ...
                                'my', 6, ...
                                'type', 'empty'), ...
            'obstacle_8x8', struct('name', 'obstacle_8x8', ...
                                   'mx', 8, ...
                                   'my', 8, ...
                                   'type', 'obstacle'));
    end

    methods (Test)
        function testFullSweepMatchesReference(testCase, full_sweep_case)
            p = vi_params();
            max_value = double(p.MAX_VALUE);
            transitions = gen_transitions('paper_mc');

            [value, penalty, ~, ~, goal_mask] = gen_test_map( ...
                full_sweep_case.mx, full_sweep_case.my, full_sweep_case.type);
            [ref_out, ref_action, ~, ~] = vi_full_reference(value, penalty, ...
                goal_mask, transitions, full_sweep_case.mx, ...
                full_sweep_case.my, 0, 15);

            ml_value = value;
            for sweep = 1:15
                [ml_value, delta0] = vi_sweep_stream_algo(ml_value, ml_value, ...
                    penalty, goal_mask, transitions, full_sweep_case.mx, ...
                    full_sweep_case.my, 0);
                [ml_value, delta1] = vi_sweep_stream_algo(ml_value, ml_value, ...
                    penalty, goal_mask, transitions, full_sweep_case.mx, ...
                    full_sweep_case.my, 1);
                if max(delta0, delta1) == 0
                    break;
                end
            end

            ml_action = compute_action_table_reference(ml_value, penalty, ...
                goal_mask, transitions, full_sweep_case.mx, ...
                full_sweep_case.my);

            free_mask = ~goal_mask & repmat( ...
                penalty ~= double(p.PENALTY_OBSTACLE), [1, 1, p.N_THETA]);
            ml_vals = ml_value(free_mask);
            ref_vals = ref_out(free_mask);

            testCase.verifyEqual(ml_vals < max_value, ref_vals < max_value, ...
                sprintf('%s: reachability mismatch', full_sweep_case.name));
            testCase.verifyEqual(ml_vals, ref_vals, ...
                sprintf('%s: value mismatch', full_sweep_case.name));
            testCase.verifyEqual(ml_action(free_mask), ref_action(free_mask), ...
                sprintf('%s: action mismatch', full_sweep_case.name));
            testCase.verifyTrue(all(ml_value(goal_mask) == 0), ...
                sprintf('%s: goal values changed', full_sweep_case.name));
        end

        function testPaperVsFpgaMetricsRemainFinite(testCase)
            p = vi_params();
            map_x = 8;
            map_y = 8;
            transitions = gen_transitions('paper_mc');
            [value, penalty, ~, ~, goal_mask] = ...
                gen_test_map(map_x, map_y, 'obstacle');

            [paper_value, paper_action, paper_sweeps, paper_delta] = ...
                vi_full_reference(value, penalty, goal_mask, transitions, ...
                    map_x, map_y, 0, 15);

            fpga_value = value;
            fpga_sweeps = 0;
            fpga_delta = inf;
            for sweep = 1:15
                [fpga_value, delta0] = vi_sweep_stream_algo(fpga_value, ...
                    fpga_value, penalty, goal_mask, transitions, ...
                    map_x, map_y, 0);
                [fpga_value, delta1] = vi_sweep_stream_algo(fpga_value, ...
                    fpga_value, penalty, goal_mask, transitions, ...
                    map_x, map_y, 1);
                fpga_sweeps = sweep;
                fpga_delta = max(delta0, delta1);
                if fpga_delta == 0
                    break;
                end
            end

            fpga_action = compute_action_table_reference(fpga_value, penalty, ...
                goal_mask, transitions, map_x, map_y);

            free_mask = ~goal_mask & repmat( ...
                penalty ~= double(p.PENALTY_OBSTACLE), [1, 1, p.N_THETA]);
            total_states = nnz(free_mask);
            value_diff_pct = 100 * nnz((paper_value ~= fpga_value) & free_mask) ...
                / total_states;
            action_diff_pct = 100 * nnz((paper_action ~= fpga_action) & free_mask) ...
                / total_states;
            denom = max(paper_value(free_mask), 1);
            mean_abs_pct = 100 * mean( ...
                abs(fpga_value(free_mask) - paper_value(free_mask)) ./ denom);

            fprintf(['paper_vs_fpga.value_mismatch_pct=%.4f%%\n' ...
                     'paper_vs_fpga.action_mismatch_pct=%.4f%%\n' ...
                     'paper_vs_fpga.mean_abs_value_pct=%.4f%%\n' ...
                     'paper_vs_fpga.paper_sweeps=%d final_delta=%.0f\n' ...
                     'paper_vs_fpga.fpga_sweeps=%d final_delta=%.0f\n'], ...
                value_diff_pct, action_diff_pct, mean_abs_pct, ...
                paper_sweeps, paper_delta, fpga_sweeps, fpga_delta);

            testCase.verifyTrue(isfinite(value_diff_pct));
            testCase.verifyTrue(isfinite(action_diff_pct));
            testCase.verifyTrue(isfinite(mean_abs_pct));
        end
    end
end
