classdef TestBlockRefine < TestBase
%TESTBLOCKREFINE Equivalence tests for block-frontier VI.

    properties (TestParameter)
        bench_case = struct( ...
            'empty_8',     struct('map_x',  8, 'map_y',  8, 'type', 'empty',    'opts', struct()), ...
            'obstacle_8',  struct('map_x',  8, 'map_y',  8, 'type', 'obstacle', 'opts', struct()), ...
            'random_8',    struct('map_x',  8, 'map_y',  8, 'type', 'random',   'opts', struct('density', 0.15, 'seed', 42)), ...
            'empty_16',    struct('map_x', 16, 'map_y', 16, 'type', 'empty',    'opts', struct()), ...
            'obstacle_16', struct('map_x', 16, 'map_y', 16, 'type', 'obstacle', 'opts', struct()), ...
            'random_16',   struct('map_x', 16, 'map_y', 16, 'type', 'random',   'opts', struct('density', 0.15, 'seed', 42)));
    end

    methods (Test)
        function testBlockRefineMatchesReference(testCase, bench_case)
            [value0, penalty, ~, ~, goal_mask] = gen_test_map( ...
                bench_case.map_x, bench_case.map_y, bench_case.type, ...
                bench_case.opts);
            transitions = gen_transitions('paper_mc');
            max_iters = 800;

            v_ref = vi_full_reference(value0, penalty, goal_mask, transitions, ...
                bench_case.map_x, bench_case.map_y, 0, max_iters);

            v_block = vi_block_refine(value0, penalty, goal_mask, transitions, ...
                bench_case.map_x, bench_case.map_y, max_iters, 4, 4, 2, 0);

            testCase.verifyEqual(v_block, v_ref);
        end
    end
end
