function p = vi_params()
%VI_PARAMS Shared constants for the MATLAB streaming VI kernel.
%   Mirrors fpga/hls/stream/src/vi_stream_types.h.

    p = struct( ...
        'N_ACTIONS', 6, ...
        'N_THETA', 60, ...
        'HALO_MAX', 6, ...
        'WINDOW_ROWS', 13, ...
        'STRIP_W_MAX', 145, ...
        'BUF_W', 157, ...
        'RESOLUTION_XY_BIT', 6, ...
        'RESOLUTION_T_BIT', 6, ...
        'PROB_BASE_BIT', 18, ...
        'PROB_BASE', 262144, ...
        'ACTION_FW', [0.3, -0.2, 0.0, 0.2, 0.0, 0.2], ...
        'ACTION_ROT', [0.0, 0.0, -20.0, -20.0, 20.0, 20.0], ...
        'MAX_OUTCOMES', 10, ...
        'TRANS_WORD_STRIDE', 21, ...
        'TRANS_TABLE_SIZE', 7560, ...
        'SOC_MAP_X_MAX', 8, ...
        'SOC_MAP_Y_MAX', 8, ...
        'SOC_PENALTY_WORD_MAX', 64, ...
        'SOC_TRANS_OFFSET_WORD', 8192, ...
        'MAX_VALUE', uint16(hex2dec('FFFF')), ...
        'PENALTY_OBSTACLE', uint16(hex2dec('FFFF')), ...
        'PENALTY_GOAL', uint16(hex2dec('FFFE')) ...
    );
end
